services:
    reviews_php:
        image: teso/reviews:1.0
        container_name: reviews_php
        build:
            context: ./
        depends_on:
            - reviews_mysql
        volumes:
            - ./:/var/www/reviews/
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        environment:
            XDEBUG_CONFIG: "idekey=PHPSTORM mode=debug client_host=172.17.0.1 client_port=9003"
            PHP_IDE_CONFIG: "serverName=reviews"
        restart: always
    reviews_mysql:
        image: mysql:5.7.38
        container_name: reviews_mysql
        user: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root_secret
            - MYSQL_DATABASE=reviews
            - MYSQL_USER=reviews_user
            - MYSQL_PASSWORD=reviews_secret
        ports:
            - 33060:3306
        volumes:
            - ../reviews_database/:/var/lib/mysql/
        restart: always
    reviews_nginx:
        image: nginx:latest
        container_name: reviews_nginx
        depends_on:
            - reviews_php
        volumes_from:
            - reviews_php
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
